Play travis
Otus-DevOps-2021-08/levkins_infra pull request #1
Opened 2021-09-20 18:59 UTC by levkins

2021-09-21 08:12 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. Оставил комментарий к файлу, дз возвращаю на доработку =)

2021-09-21 08:12 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Вот сюда смотрим внимательно, все тесты должны быть зелеными =)

2021-09-21 19:41 UTC, levkins commented
Исправлены ошибки и откорректирован под задание (начал делать следующее в данной ветке)

2021-09-21 19:43 UTC, levkins commented
Ночным взглядом перепутал close & clone.

2021-09-23 09:11 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-09-27 19:58 UTC, merged